auto_server: true
blas_num_threads: 1
clean: false
cleanup_textgrids: true
database_limited_mode: false
debug: false
github_token: null
hf_token: null
num_jobs: 3
overwrite: false
profiles: {}
quiet: false
seed: 0
single_speaker: false
temporary_directory: /app/models
use_mp: true
use_postgres: false
use_threading: true
verbose: false
